Sports_News/Controllers/HomeController.cs
using Antlr.Runtime.Tree;
using Sports_News.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sports_News.Controllers
{
    public class HomeController : Controller
    {
        private UserEntities _db = new UserEntities();
        public ActionResult Index()
        {
            Session["login"] = false;
            List<Post> posts = new List<Post>();
            PostEntities postEntities = new PostEntities();
            posts = postEntities.showNewPosts();
            return View(posts);
        }

        public ActionResult About()
        {
            TempData["ErrorMessage"] = "Your application description page.";

            return View();
        }
        [HttpPost]
        public ActionResult Search(FormCollection formCollection)
        {
            List<Post> posts = new List<Post>();
            PostEntities postEntities = new PostEntities();
            posts = postEntities.showPostWithSearch(formCollection["search"]);
            return View(posts);
        }
        public ActionResult Admin()
        {
            if (Convert.ToBoolean(Session.Contents["login"]))
            {
                PostEntities postEntities = new PostEntities();
                CategoryEntities categoryEntities = new CategoryEntities();
                UserEntities userEntities = new UserEntities();
                CountData cd = new CountData();
                cd.CountPosts = postEntities.Posts.Count();
                cd.CountPostPublic = postEntities.Posts.Where(x => x.published == 0).Count();
                cd.CountPostPrivate = cd.CountPosts - cd.CountPostPublic;
                cd.CountCategorys = categoryEntities.Categories.Count();
                cd.CountUsers = userEntities.Users.Count();
                cd.CountUserAdmin = userEntities.Users.Where(x => x.role == 1).Count();
                cd.CountUserEmp = cd.CountUsers - cd.CountUserAdmin;
                return View(cd);
            }
            return RedirectToAction("About", "Home", new { area = "" });
        }
        public ActionResult test()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult test(FormCollection formCollection)
        {
            int a = Convert.ToInt32(formCollection["a"]);
            int b = Convert.ToInt32(formCollection["b"]);
            int sum = a + b;
            TempData["sum"] = sum;
            return RedirectToAction("test", "Home", new { area = "" });
        }
    }
}

Sports_News/Controllers/PostController.cs
using Sports_News.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sports_News.Controllers
{
    public class PostController : Controller
    {
        // GET: Product
        public ActionResult Show_post()
        {
            if(Convert.ToBoolean(Session.Contents["login"]))
            {
                PostEntities postEntities = new PostEntities();
                List<Post> posts = postEntities.Posts.ToList();
                return View(posts);
            }
            return RedirectToAction("About", "Home", new { area = "" });
        }
        public ActionResult Show_postWithCategory(string id)
        {
            PostEntities postEntities = new PostEntities();
            List<Post> posts = new List<Post>();
            posts = postEntities.showPostWithCategory(Convert.ToInt32(id));
            return View(posts);
        }
        //------------------------------------------
        public ActionResult Show_post_details(int id)
        {
            PostEntities postEntities = new PostEntities();
            Post post = postEntities.Posts.Single(p => p.id == id);
            return View(post);
        }
        public ActionResult Add_post()
        {
            if (Convert.ToBoolean(Session.Contents["login"]))
            {
                CategoryEntities categoryEntities = new CategoryEntities();
                List<Category> categories = categoryEntities.Categories.ToList();
                return View(categories);
            }
            return RedirectToAction("About", "Home", new { area = "" });
        }
        //-----------------------------
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Add_post(FormCollection formCollection, HttpPostedFileBase file)
        {
            if (Convert.ToBoolean(Session.Contents["login"]))
            {
                byte pub = 1;
                string fileName = "";
                if (!String.IsNullOrEmpty(formCollection["published"]) && formCollection["published"] == "true")
                {
                    pub = 0;
                }
                if (ModelState.IsValid)
                {
                    try
                    {
                        if (file != null)
                        {
                            Random r = new Random();
                            fileName = r.Next(0, 100000) + r.Next(0, 100000) + file.FileName; 
                            string path = Path.Combine(Server.MapPath("~/Content/images"), Path.GetFileName(fileName));
                            file.SaveAs(path);
                        }
                        ViewBag.FileStatus = "File uploaded successfully.";
                    }
                    catch (Exception)
                    {
                        ViewBag.FileStatus = "Error while file uploading.";
                    }
                }
                Post post = new Post();
                post.user_id = Convert.ToInt32(Session["role"]);
                post.value_category = Convert.ToInt32(formCollection["category"]);
                post.title = formCollection["title"];
                post.published = pub;
                post.describes = formCollection["describes"];
                post.body = formCollection["body_post"];
                post.image = fileName;
                post.created_at = Convert.ToDateTime(DateTime.Now.ToString("yyyy-MM-dd HH:mm:sszzz"));
                PostEntities postEntities = new PostEntities();
                postEntities.addPost(post);
                return RedirectToAction("Show_post");
            }
            return RedirectToAction("About", "Home", new { area = "" });
        }
        //-----------------------------
        public ActionResult Edit_post(int id)
        {
            if (Convert.ToBoolean(Session.Contents["login"]))
            {
                PostEntities postEntities = new PostEntities();
                CategoryEntities categoryEntities = new CategoryEntities();
                MultipleModels mul = new MultipleModels();
                mul.Posts = postEntities.showPostDetail(id);
                mul.Categorys = categoryEntities.listCategory();
                return View(mul);
            }
            return RedirectToAction("About", "Home", new { area = "" });
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit_post(FormCollection formCollection, HttpPostedFileBase file)
        {
            if (Convert.ToBoolean(Session.Contents["login"]))
            {
                byte pub = 1;
                string fileName = "";
                if (!String.IsNullOrEmpty(formCollection["published"]) && formCollection["published"] == "true")
                {
                    pub = 0;
                }
                if (ModelState.IsValid)
                {
                    try
                    {
                        if (file != null)
                        {
                            Random r = new Random();
                            fileName = r.Next(0, 100000) + r.Next(0, 100000) + file.FileName;
                            string path = Path.Combine(Server.MapPath("~/Content/images"), Path.GetFileName(fileName));
                            file.SaveAs(path);
                        }
                        else
                        {
                            fileName = null;
                        }
                        ViewBag.FileStatus = "File uploaded successfully.";
                    }
                    catch (Exception)
                    {
                        ViewBag.FileStatus = "Error while file uploading.";
                    }
                }
                Post post = new Post();
                post.id = Convert.ToInt32(formCollection["id"]);
                post.user_id = Convert.ToInt32(Session["id"]);
                post.value_category = Convert.ToInt32(formCollection["category"]);
                post.title = formCollection["title"];
                post.published = pub;
                post.describes = formCollection["describes"];
                post.body = formCollection["body_post"];
                post.image = fileName;
                post.created_at = Convert.ToDateTime(DateTime.Now.ToString("yyyy-MM-dd HH:mm:sszzz"));
                PostEntities postEntities = new PostEntities();
                postEntities.editPost(post);
                return RedirectToAction("Show_post");
            }
            return RedirectToAction("About", "Home", new { area = "" });
        }

        public ActionResult Delete_post(int id)
        {
            if (Convert.ToBoolean(Session.Contents["login"]))
            {
                PostEntities postEntities = new PostEntities();
                postEntities.deletePost(id);
                return RedirectToAction("Show_post");
            }
            return RedirectToAction("About", "Home", new { area = "" });
        }
    }
}

Sports_News/Views/Home/About.cshtml
@model Sports_News.Models.Post
@{
    ViewBag.Title = "About";
}
    <section class="row flexbox-container">
        <div class="col-xl-7 col-md-8 col-12 d-flex justify-content-center">
            <div class="card auth-card bg-transparent shadow-none rounded-0 mb-0 w-100">
                <div class="card-content">
                    <div class="card-body text-center">
                        <img src="../../../Content/images/pages/404.png" class="img-fluid align-self-center" alt="branding logo">
                        <h1 class="font-large-2 my-1">404 - Page Not Found!</h1>
                        <p class="p-2">
                            paraphonic unassessable foramination Caulopteris worral Spirophyton encrimson esparcet aggerate chondrule
                            restate whistler shallopy biosystematy area bertram plotting unstarting quarterstaff.
                        </p>
                        <a class="btn btn-primary btn-lg mt-2" href="/">Back to Home</a>
                    </div>
                </div>
            </div>
        </div>
    </section>

Sports_News/Views/Home/Admin.cshtml
@using Sports_News.Models;
@model CountData
@{
    ViewBag.Title = "Admin";
}
<div class="content-overlay"></div>
<div class="header-navbar-shadow"></div>
<div class="content-wrapper">
    <section id="statistics-card">
        <div class="row">
            <div class="col-lg-4 col-sm-6 col-12">
                <div class="card">
                    <div class="card-header d-flex align-items-start pb-0">
                        <div>
                            <h2 class="text-bold-700 mb-0">@Model.CountUsers</h2>
                            <p>Tài khoản đã đăng ký</p>
                        </div>
                        <div class="avatar bg-rgba-primary p-50 m-0">
                            <div class="avatar-content">
                                <i class="feather icon-users text-primary font-medium-5"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-sm-6 col-12">
                <div class="card">
                    <div class="card-header d-flex align-items-start pb-0">
                        <div>
                            <h2 class="text-bold-700 mb-0">@Model.CountPosts</h2>
                            <p>Bài viết</p>
                        </div>
                        <div class="avatar bg-rgba-success p-50 m-0">
                            <div class="avatar-content">
                                <i class="feather icon-credit-card text-success font-medium-5"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-sm-6 col-12">
                <div class="card">
                    <div class="card-header d-flex align-items-start pb-0">
                        <div>
                            <h2 class="text-bold-700 mb-0">@Model.CountCategorys</h2>
                            <p>Category</p>
                        </div>
                        <div class="avatar bg-rgba-danger p-50 m-0">
                            <div class="avatar-content">
                                <i class="feather icon-server text-danger font-medium-5"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xl-3 col-md-4 col-sm-6">
                <div class="card text-center">
                    <div class="card-content">
                        <div class="card-body">
                            <div class="avatar bg-rgba-info p-50 m-0 mb-1">
                                <div class="avatar-content">
                                    <i class="feather icon-eye text-info font-medium-5"></i>
                                </div>
                            </div>
                            <h2 class="text-bold-700">@Model.CountUserAdmin</h2>
                            <p class="mb-0 line-ellipsis">Tài khoản admin</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-md-4 col-sm-6">
                <div class="card text-center">
                    <div class="card-content">
                        <div class="card-body">
                            <div class="avatar bg-rgba-warning p-50 m-0 mb-1">
                                <div class="avatar-content">
                                    <i class="feather icon-message-square text-warning font-medium-5"></i>
                                </div>
                            </div>
                            <h2 class="text-bold-700">@Model.CountUserEmp</h2>
                            <p class="mb-0 line-ellipsis">Tài khoản employee</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-md-4 col-sm-6">
                <div class="card text-center">
                    <div class="card-content">
                        <div class="card-body">
                            <div class="avatar bg-rgba-danger p-50 m-0 mb-1">
                                <div class="avatar-content">
                                    <i class="feather icon-shopping-bag text-danger font-medium-5"></i>
                                </div>
                            </div>
                            <h2 class="text-bold-700">@Model.CountPostPublic</h2>
                            <p class="mb-0 line-ellipsis">Bài viết được hiển thị</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-md-4 col-sm-6">
                <div class="card text-center">
                    <div class="card-content">
                        <div class="card-body">
                            <div class="avatar bg-rgba-primary p-50 m-0 mb-1">
                                <div class="avatar-content">
                                    <i class="feather icon-heart text-primary font-medium-5"></i>
                                </div>
                            </div>
                            <h2 class="text-bold-700">@Model.CountPostPrivate</h2>
                            <p class="mb-0 line-ellipsis">Bài viết đã bị ẩn</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

Sports_News/Views/Home/Index.cshtml
@using Sports_News.Models;
@model IEnumerable<Post>
@{
    ViewBag.Title = "Home Page";
}
<div class="content-overlay"></div>
<div class="header-navbar-shadow"></div>
<div class="content-wrapper">
    <div class="content-header row">
        <div class="content-header-left col-md-9 col-12 mb-2">
            <div class="row breadcrumbs-top">
                <div class="col-12">

                </div>
            </div>
        </div>
    </div>
    <div class="content-detached content-right">
        <div class="content-body">
            <!-- Ecommerce Content Section Starts -->
            <section id="ecommerce-header">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="ecommerce-header-items">
                            <div class="result-toggler">
                                <button class="navbar-toggler shop-sidebar-toggler" type="button" data-toggle="collapse">
                                    <span class="navbar-toggler-icon d-block d-lg-none"><i class="feather icon-menu"></i></span>
                                </button>
                                <div class="search-results">

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- Ecommerce Content Section Starts -->
            <!-- background Overlay when sidebar is shown  starts-->
            <div class="shop-content-overlay"></div>
            <!-- background Overlay when sidebar is shown  ends-->
            <!-- Ecommerce Search Bar Starts -->
            <section id="ecommerce-searchbar">
                <div class="row mt-1">
                    <div class="col-sm-12">
                        <fieldset class="form-group position-relative">
                            <form action="@Url.Action("Search", "Home")" method="post">
                                <input type="text" class="form-control search-product" id="iconLeft5" placeholder="Search here" name="search">
                                <div class="form-control-position">
                                    <button type="submit" class="btn btn-sm btn-icon btn-icon rounded-circle btn-flat-success mr-1 mb-1 waves-effect waves-light"><i class="feather icon-search"></i></button>
                                </div>
                            </form>
                        </fieldset>
                    </div>
                </div>
            </section>
            <!-- Ecommerce Search Bar Ends -->
            <!-- Ecommerce Products Starts -->
            <div class="row">
                <div class="col-8">
                    <section id="ecommerce-products" class="list-view">
                        @foreach (Post post in Model)
                        {
                            <div class="card ecommerce-card" >
                                <a href="@Url.Action("Show_post_details", "Post", new { @post.id })">
                                    <div class="card-content">
                                        <div class="item-img text-center">
                                            <img src="../../../Content/images/@post.image" alt="img-placeholder" width="320" height="170">
                                        </div>
                                        <div class="card-text" style="width:100%">
                                            <div class="item-name">
                                                <h2><a href="@Url.Action("Show_post_details", "Post", new { @post.id })">@post.title</a></h2>
                                            </div>
                                            <div>
                                                <p class="item-description">
                                                    @post.describes
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        }
                    </section>
                </div>
                <div class="col-4">
                    <section>
                        <div class="card" style="margin-right:15px;">
                            <div class="card-body">
                                <h3>Tin tức nổi bật</h3>
                                <table class="table ">
                                    @foreach (Post posts in Model)
                                    {
                                        <tr>
                                            <td class="product-img">
                                                <a href="@Url.Action("Show_post_details", "Post", new { @posts.id })">
                                                    <img src="../../../Content/images/@posts.image" alt="Img placeholder" width="90px" height="60">
                                                </a>
                                            </td>
                                            <td class="product-name">
                                                <a href="@Url.Action("Show_post_details", "Post", new { @posts.id })">@posts.title</a>
                                            </td>
                                        </tr>
                                    }
                                </table>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
            <!-- Ecommerce Products Ends -->
        </div>
    </div>
    <div class="sidebar-detached sidebar-left">
        <div class="sidebar">
        </div>
    </div>
</div>

Sports_News/Views/Home/Search.cshtml
@using Sports_News.Models;
@model IEnumerable<Post>
@{
    ViewBag.Title = "Home Page";
}
<div class="content-overlay"></div>
<div class="header-navbar-shadow"></div>
<div class="content-wrapper">
    <div class="content-header row">
        <div class="content-header-left col-md-9 col-12 mb-2">
            <div class="row breadcrumbs-top">
                <div class="col-12">

                </div>
            </div>
        </div>
    </div>
    <div class="content-detached content-right">
        <div class="content-body">
            <!-- Ecommerce Content Section Starts -->
            <section id="ecommerce-header">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="ecommerce-header-items">
                            <div class="result-toggler">
                                <button class="navbar-toggler shop-sidebar-toggler" type="button" data-toggle="collapse">
                                    <span class="navbar-toggler-icon d-block d-lg-none"><i class="feather icon-menu"></i></span>
                                </button>
                                <div class="search-results">

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- Ecommerce Content Section Starts -->
            <!-- background Overlay when sidebar is shown  starts-->
            <div class="shop-content-overlay"></div>
            <!-- background Overlay when sidebar is shown  ends-->
            <!-- Ecommerce Search Bar Starts -->
            <section id="ecommerce-searchbar">
                <div class="row mt-1">
                    <div class="col-sm-12">
                        <fieldset class="form-group position-relative">
                            <form action="@Url.Action("Search", "Home") " method="post">
                                <input type="text" name="search" class="form-control search-product" id="iconLeft5" placeholder="Search here">
                                <div class="form-control-position">
                                    <button type="submit" class="btn btn-sm btn-icon btn-icon rounded-circle btn-flat-success mr-1 mb-1 waves-effect waves-light"><i class="feather icon-search"></i></button>
                                </div>
                            </form>
                        </fieldset>
                    </div>
                </div>
            </section>
            <!-- Ecommerce Search Bar Ends -->
            <!-- Ecommerce Products Starts -->
            <section id="ecommerce-products" class="list-view">
                @foreach (Post post in Model)
                {
                    <div class="card ecommerce-card">
                        <a href="@Url.Action("Show_post_details", "Post", new { @post.id })">
                            <div class="card-content">
                                <div class="item-img text-center">
                                    <img src="../../../Content/images/@post.image" alt="img-placeholder" width="320" height="170">
                                </div>
                                <div class="card-text">
                                    <div class="item-name">
                                        <h2><a href="@Url.Action("Show_post_details", "Post", new { @post.id })">@post.title</a></h2>
                                    </div>
                                    <div>
                                        <p class="item-description">
                                            @post.describes
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                }
            </section>
            <!-- Ecommerce Products Ends -->
            <!-- Ecommerce Pagination Starts -->
            <section id="ecommerce-pagination">
                <div class="row">
                    <div class="col-sm-12">
                        <nav aria-label="Page navigation example">
                            <ul class="pagination justify-content-center mt-2">
                                <li class="page-item prev-item"><a class="page-link" href="#"></a></li>
                                <li class="page-item active"><a class="page-link" href="#">1</a></li>
                                <li class="page-item"><a class="page-link" href="#">2</a></li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item" aria-current="page"><a class="page-link" href="#">4</a></li>
                                <li class="page-item"><a class="page-link" href="#">5</a></li>
                                <li class="page-item"><a class="page-link" href="#">6</a></li>
                                <li class="page-item"><a class="page-link" href="#">7</a></li>
                                <li class="page-item next-item"><a class="page-link" href="#"></a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </section>
            <!-- Ecommerce Pagination Ends -->

        </div>
    </div>
    <div class="sidebar-detached sidebar-left">
        <div class="sidebar">
            <!-- Ecommerce Sidebar Starts -->
            <!-- Ecommerce Sidebar Ends -->

        </div>
    </div>
</div>

Sports_News/Views/Home/test.cshtml
@{
    ViewBag.Title = "test";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>test</h2>
<form action="test" method="post" id="identifier">
    @Html.AntiForgeryToken()
    <label>a</label>
    <input type="text" name="a" /><br />
    <label>b</label>
    <input type="text" name="b" /><br />
    <input type="submit" name="btn" value="ket qua" />
</form>
@if (TempData["sum"] != null)
{
    <p class="px-2" style="color: maroon;">ket qua: @TempData["sum"]</p>
}