Sports_News/Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Sports_News.Models
{
    public class Category
    {
        public int id { get; set; }
        public string name { get; set; }
    }
}

Sports_News/Controllers/CategoryController.cs
using Sports_News.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sports_News.Controllers
{
    public class CategoryController : Controller
    {
        // GET: Category
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Show_category()
        {
            CategoryEntities categoryEntities = new CategoryEntities();
            List<Category> categories = categoryEntities.Categories.ToList();
            return View(categories);
        }
        public ActionResult Add_category()
        {
            if (!String.IsNullOrEmpty(Convert.ToString(Session["role"])) && Convert.ToInt32(Session["role"]) == 1)
            {
                return View();
            }
            return RedirectToAction("About", "Home", new { area = "" });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Add_category(FormCollection formCollection)
        {
            if (!String.IsNullOrEmpty(Convert.ToString(Session["role"])) && Convert.ToInt32(Session["role"]) == 1)
            {
                Category category = new Category();
                category.name = formCollection["name"];
                CategoryEntities categoryEntities = new CategoryEntities();
                categoryEntities.addCategory(category);
                return RedirectToAction("Show_category");
            }
            return RedirectToAction("About", "Home", new { area = "" });
        }
        public ActionResult Edit_category(int id)
        {
            if (!String.IsNullOrEmpty(Convert.ToString(Session["role"])) && Convert.ToInt32(Session["role"]) == 1)
            {
                CategoryEntities categoryEntities = new CategoryEntities();
                Category category = categoryEntities.Categories.Single(p => p.id == id);
                return View(category);
            }
            return RedirectToAction("About", "Home", new { area = "" });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit_category(FormCollection formCollection)
        {
            if (!String.IsNullOrEmpty(Convert.ToString(Session["role"])) && Convert.ToInt32(Session["role"]) == 1)
            {
                Category category = new Category();
                category.name = formCollection["name"];
                category.id = Convert.ToInt32(formCollection["id"]);
                CategoryEntities categoryEntities = new CategoryEntities();
                categoryEntities.editCategory(category);
                return RedirectToAction("Show_category");
            }
            return RedirectToAction("About", "Home", new { area = "" });
        }

        public ActionResult Delete_category(int id)
        {
            if (!String.IsNullOrEmpty(Convert.ToString(Session["role"])) && Convert.ToInt32(Session["role"]) == 1)
            {
                CategoryEntities categoryEntities = new CategoryEntities();
                categoryEntities.deleteCategory(id);
                return RedirectToAction("Show_category");
            }
            return RedirectToAction("About", "Home", new { area = "" });
        }
    }
}

Sports_News/Views/Category/Add_category.cshtml
@{
    ViewBag.Title = "Add_category";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content-overlay"></div>
<div class="header-navbar-shadow"></div>
<div class="content-wrapper">
    <div class="content-header row">
        <div class="content-header-left col-md-9 col-12 mb-2">
            <div class="row breadcrumbs-top">
                <div class="col-12">
                    <h2 class="content-header-title float-left mb-0">Thêm mới Category</h2>
                    <div class="breadcrumb-wrapper col-12">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="#">Trang chủ</a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="@Url.Action("Show_category", "Category")">Quản lý Category</a>
                            </li>
                            <li class="breadcrumb-item active">
                                Thêm mới Category
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
            <div class="form-group breadcrum-right">
                <div class="dropdown">
                    <button class="btn-icon btn btn-primary btn-round btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="feather icon-settings"></i></button>
                    <div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="#">Chat</a><a class="dropdown-item" href="#">Email</a><a class="dropdown-item" href="#">Calendar</a></div>
                </div>
            </div>
        </div>
    </div>
    <div class="content-body">
        <section class="full-editor">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Quản lý Category</h4>
                    </div>
                    <div class="card-content collapse show">
                        <div class="card-body">
                            <div class="add-new-data-sidebar">
                                <div class="overlay-bg"></div>
                                <div class="add-new-data">
                                    <div class="data-items pb-3">
                                        <div class="data-fields px-2 mt-3">
                                            <form action="Add_category" method="post" id="identifier">
                                                @Html.AntiForgeryToken()
                                                <div class="row">
                                                    <div class="col-sm-12 data-field-col">
                                                        <label for="data-menu">Tên Category</label>
                                                        <input type="text" class="form-control" id="data-menu" name="name">
                                                    </div>
                                                    <div class="col-sm-12 data-field-col" style="text-align:center;">
                                                        <br />
                                                        <br />
                                                        <input type="submit" class="btn btn-primary" value="Thêm mới" name="btn_add_user" />
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>

Sports_News/Views/Category/Edit_category.cshtml
@using Sports_News.Models;
@model Sports_News.Models.Category
@{
    ViewBag.Title = "Edit_category";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="content-overlay"></div>
<div class="header-navbar-shadow"></div>
<div class="content-wrapper">
    <div class="content-header row">
        <div class="content-header-left col-md-9 col-12 mb-2">
            <div class="row breadcrumbs-top">
                <div class="col-12">
                    <h2 class="content-header-title float-left mb-0">Sửa Menu</h2>
                    <div class="breadcrumb-wrapper col-12">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="#">Trang chủ</a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="@Url.Action("Show_category", "Category")">Quản lý Menu</a>
                            </li>
                            <li class="breadcrumb-item active">
                                Sửa Menu
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
            <div class="form-group breadcrum-right">
                <div class="dropdown">
                    <button class="btn-icon btn btn-primary btn-round btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="feather icon-settings"></i></button>
                    <div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="#">Chat</a><a class="dropdown-item" href="#">Email</a><a class="dropdown-item" href="#">Calendar</a></div>
                </div>
            </div>
        </div>
    </div>
    <div class="content-body">
        <section class="full-editor">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Quản lý Menu</h4>
                    </div>
                    <div class="card-content collapse show">
                        <div class="card-body">
                            <div class="add-new-data-sidebar">
                                <div class="overlay-bg"></div>
                                <div class="add-new-data">
                                    <div class="data-items pb-3">
                                        <div class="data-fields px-2 mt-3">
                                            <form action="Edit_category" method="post" id="identifier">
                                                @Html.AntiForgeryToken()
                                                <input type="text" id="data-tilte" hidden name="id" value="@Model.id">
                                                <div class="row">
                                                    <div class="col-sm-12 data-field-col">
                                                        <label for="data-menu">Tên menu</label>
                                                        <input type="text" class="form-control" id="data-menu" value="@Model.name" name="name">
                                                    </div>
                                                    <div class="col-sm-12 data-field-col" style="text-align:center;">
                                                        <br />
                                                        <br />
                                                        <input type="submit" class="btn btn-primary" value="Update" name="btn_add_user" />
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>

Sports_News/Views/Category/Show_category.cshtml
@using Sports_News.Models;
@model IEnumerable<Category>
@{
    ViewBag.Title = "Show_category";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content-overlay"></div>
<div class="header-navbar-shadow"></div>
<div class="content-wrapper">
    <div class="content-header row">
        <div class="content-header-left col-md-9 col-12 mb-2">
            <div class="row breadcrumbs-top">
                <div class="col-12">
                    <h2 class="content-header-title float-left mb-0">Quản lý Category</h2>
                    <div class="breadcrumb-wrapper col-12">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="#">Trang chủ</a>
                            </li>
                            <li class="breadcrumb-item active">
                                Quản lý Category
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">

        </div>
    </div>
    <div class="content-body">
        <!-- Data list view starts -->
        <section id="data-thumb-view" class="data-thumb-view-header">
            <!-- dataTable starts -->
            <div class="table-responsive">
                <table class="table data-thumb-view2">
                    <thead>
                        <tr>
                            <th></th>
                            <th>ID</th>
                            <th>Tên category</th>
                            <th>ACTION</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (Category category in Model)
                        {
                            <tr>
                                <td></td>
                                <td class="product-email">@category.id</td>
                                <td class="product-username">@category.name</td>
                                <td class="product-action">
                                    <a href="Edit_category/@category.id"><i class="feather icon-edit"></i></a>
                                    <a href="Delete_category/@category.id"><i class="feather icon-trash"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- dataTable ends -->
        </section>
        <!-- Data list view end -->
    </div>
</div>